#!/bin/bash
# Script para ejecutar la migración 0011_create_metrados_liquidaciones en Supabase

echo "=========================================="
echo "Ejecutando Migración: metrados_liquidaciones"
echo "=========================================="
echo ""
echo "OPCIÓN 1: Usando Supabase CLI (recomendado)"
echo "-------------------------------------------"
echo "npm install -g supabase"
echo "supabase link"
echo "supabase db push"
echo ""
echo "OPCIÓN 2: Manual en Supabase Dashboard"
echo "-------------------------------------------"
echo "1. Ir a: https://app.supabase.com"
echo "2. Seleccionar tu proyecto"
echo "3. SQL Editor → New Query"
echo "4. Copiar contenido de: supabase/migrations/0011_create_metrados_liquidaciones.sql"
echo "5. Ejecutar"
echo ""
echo "OPCIÓN 3: Desde psql (si tienes PostgreSQL local conectado)"
echo "-------------------------------------------"
echo "psql -h your-db.supabase.co -p 5432 -U postgres -d postgres < supabase/migrations/0011_create_metrados_liquidaciones.sql"
echo ""
echo "✅ Después de ejecutar, verificar:"
echo "   SELECT tablename FROM pg_tables WHERE tablename = 'metrados_liquidaciones';"
echo ""
echo "✅ Verificar índices creados:"
echo "   SELECT indexname FROM pg_indexes WHERE tablename = 'metrados_liquidaciones';"
